### PR TITLE
Fix view refresh and display tags in detail panel

### LINKED ISSUE #178: GUI  becomes blank after using tag/note/circle feature in view mode
When a user is viewing a single contact using the view command, using the tag/ note/ circle feature to that contact causes the contact display area in the GUI to go blank. The contact is still in the address book, but nothing is displayed until the user exits the app or type list. User might not know how to continue using the app

### LINKED ISSUE #183: Tag error message
- Error message should tell user that tag must have no spaces. 
e.g. “tagadd 1 t/bro  ther” leads to “Tags must be 1-20 chars” 

- Including a “-“ hyphen results in error message, but error message says it’s allowed 

- Error message should tell user that can include “only lower case”

Image

### LINKED ISSUE #184: Tag count limit
Maybe set a limit of 8 tags, else will overflow in UI 
Image

### LINKED ISSUE #186: Tag code inconsistency
Tag.java uses VALIDATION_REGEX = "\\p{Alnum}+" 
TagAddCommand uses if (!tag.tagName.matches("[a-z0-9\\-]{1,20}")) { 

choose one way of verifying, else might cause inconsistency

### LINKED ISSUE #190: Tagadd not compatible with View
running “view” then “tagadd”/ “note” results in an empty person card (keep the viewed person there)

### LINKED ISSUE #192: UI organise tags better
- UI can organise the tags in cleaner columns n rows

### PR DESCRIPTION
**Pull request by Tian-Jiarui**
Closes #178 
Closes #183
Closes #184
Closes #186
Closes #190
Closes #192

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 1]
```diff
@@ -69,7 +69,10 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         Person personToView = lastShownList.get(targetIndex.getZeroBased());
-        Predicate<Person> predicate = p -> p.equals(personToView);
```
Comment (sr-magicturtle) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java]: Great spot! .equals() checks all fields for a person, so when we ran any other command, the displayed person is no longer the same exact person.
