### PR TITLE
Fix Followup date and add followup removal

### LINKED ISSUE #170: Removal of FollowUpDate
Follow up date cannot be removed once added.

### LINKED ISSUE #180: Followup allows unrealistic future dates
While it is not wrong, followup allows unrealistic dates eg. 9999-12-31 to be added to a contact. Would be good to have a limit to how long ahead the dates can be added.

### PR DESCRIPTION
**Pull request by Tian-Jiarui**
Closes #170 
Closes #180

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/SetFollowUpCommand.java [hunk 1]
```diff
@@ -16,28 +15,29 @@
...
+            + "Parameters: INDEX d/FOLLOW_UP_DATE\n"
+            + "Example: " + COMMAND_WORD + " 1 d/2026-12-31";
 
-    public static final String MESSAGE_SET_FOLLOW_UP_SUCCESS =
-            "Set follow up date for Person: %1$s";
-
-    private static final Logger logger = LogsCenter.getLogger(SetFollowUpCommand.class);
+    public static final String MESSAGE_SET_FOLLOW_UP_SUCCESS = "Set follow up date for: %1$s";
+    public static final String MESSAGE_PAST_DATE_WARNING =
+            "Warning: follow up date is before today.";
```
Comment (legendgirlie47) [inline src/main/java/seedu/address/logic/commands/SetFollowUpCommand.java]: Good addition of warning instead of validation as it will help to prevent bugs!
